@startuml did-flow
skinparam backgroundColor white
skinparam defalutFontSize 12
skinparam defaultFontName Segoe UI Semibold
skinparam defaultAlign centre
<style>
  sequenceDiagram {
    reference {
      BackGroundColor #ffffff
    }
}
</style>
skinparam sequence {
    ArrowColor #000066
    ActorBorderColor #000066


    ParticipantBorderColor #000066
    ParticipantBackgroundColor #F0F9FF
    ParticipantColor #ffffff

    ActorBackgroundColor #ffffff
}
skinparam ResponseMessageBelowArrow true
!pragma teoz true

actor "Holder" as holder
boundary ":VCServiceForm" as form
control ":VCService" as system
entity ":VC" as vc
actor "IPFS Service" as ipfs
actor "Blockchain" as blockchain

holder -> form : request verify a VC()
activate holder
activate form
form -> ipfs: get a VC()
activate ipfs
deactivate ipfs
form -> system: verify a VC()
activate system
system -> blockchain: verify a VC()
activate blockchain
deactivate blockchain
deactivate system
form --> holder: success

autonumber
